"""
@dt_architect — Device Tree Architect Agent
Converts hardware_map.json → Linux Device Tree Source (.dts).
Applies pinmux conflict detection before generating output.
"""
import re
from typing import Any

# ── Pinmux conflict checker ─────────────────────────────────────────────────────

def check_pinmux_conflicts(peripherals: list[dict]) -> list[tuple[str, str, str]]:
    """
    Returns list of (pin, ptype1_id, ptype2_id) conflicts.
    """
    pin_map: dict[str, str] = {}
    conflicts = []
    for p in peripherals:
        addr = p.get("address", "")
        pid  = p["id"]
        if addr and addr in pin_map:
            conflicts.append((addr, pin_map[addr], pid))
        elif addr:
            pin_map[addr] = pid
    return conflicts


# ── DTS node generators ─────────────────────────────────────────────────────────

_COMPATIBLE_MAP = {
    "i2c":      "arm,primecell-i2c",
    "spi":      "arm,pl022",
    "uart":     "arm,pl011",
    "gpio":     "arm,pl061",
    "pwm":      "arm,pl050",
    "usb":      "usb-ehci",
    "ethernet": "snps,dwmac",
    "can":      "bosch,m_can",
    "hdmi":     "hdmi-connector",
    "camera":   "mipi-csi2",
    "other":    "generic-device",
}

_BASE_ADDR_MAP = {
    "i2c":      0xFE804000,
    "spi":      0xFE204000,
    "uart":     0xFE201000,
    "gpio":     0xFE200000,
    "pwm":      0xFE20C000,
    "usb":      0xFD500000,
    "ethernet": 0xFD580000,
    "can":      0xFE2D0000,
    "hdmi":     0xFE700000,
    "camera":   0xFE801000,
    "other":    0xFF000000,
}

def _peripheral_node(p: dict, idx: int) -> str:
    ptype  = p.get("type", "other")
    compat = _COMPATIBLE_MAP.get(ptype, "generic-device")
    addr   = p.get("address", "")
    reg_addr = int(addr, 16) if addr.startswith("0x") else (_BASE_ADDR_MAP.get(ptype, 0xFF000000) + idx * 0x1000)
    reg_hex = f"{reg_addr:08x}"
    voltage = p.get("voltage", "3.3V")
    regulator = p.get("regulator", "vcc_3v3").replace("-", "_")
    bus_num = re.sub(r"\D", "", p.get("bus", "0")) or "0"

    common = f"""\t\t{p['id']}: {ptype}@{reg_hex} {{
\t\t\tcompatible = "{compat}";
\t\t\treg = <0x0 0x{reg_hex} 0x0 0x1000>;
\t\t\t#address-cells = <1>;
\t\t\t#size-cells = <0>;
\t\t\tstatus = "okay";
\t\t\tvcc-supply = <&{regulator}>;
\t\t\t/* {p.get('description', p['name'])} */"""

    extras = ""
    if ptype == "i2c":
        extras = f"""
\t\t\tclock-frequency = <100000>;
\t\t\t#address-cells = <1>;
\t\t\t#size-cells = <0>;"""
    elif ptype == "spi":
        extras = f"""
\t\t\t#address-cells = <1>;
\t\t\t#size-cells = <0>;
\t\t\tclock-names = "spiclk", "apb_pclk";
\t\t\tnum-cs = <1>;"""
    elif ptype == "uart":
        extras = f"""
\t\t\tclock-names = "uartclk", "apb_pclk";
\t\t\tinterrupts = <GIC_SPI {16 + int(bus_num)} IRQ_TYPE_LEVEL_HIGH>;"""
    elif ptype == "gpio":
        extras = f"""
\t\t\tgpio-controller;
\t\t\t#gpio-cells = <2>;
\t\t\tinterrupt-controller;
\t\t\t#interrupt-cells = <2>;"""
    elif ptype == "ethernet":
        extras = f"""
\t\t\tclock-names = "stmmaceth", "pclk", "ptp_ref";
\t\t\tphy-mode = "rgmii-id";
\t\t\tmax-speed = <1000>;"""

    return f"{common}{extras}\n\t\t}};"


def _regulator_node(rail: dict) -> str:
    name    = rail["name"].replace("-", "_")
    voltage = rail.get("voltage", "3.3V")
    mv      = int(float(re.sub(r"[Vv]", "", voltage)) * 1_000_000)
    return f"""\t{name}: regulator-{name} {{
\t\tcompatible = "regulator-fixed";
\t\tregulator-name = "{rail['name']}";
\t\tregulator-min-microvolt = <{mv}>;
\t\tregulator-max-microvolt = <{mv}>;
\t\tregulator-always-on;
\t}};"""


# ── Public API ──────────────────────────────────────────────────────────────────

def run(hw_map: dict, selected_ids: list[str]) -> str:
    board_name = hw_map.get("board_name", "Custom")
    soc        = hw_map.get("soc", "Unknown SoC")
    arch       = hw_map.get("arch", "arm64")
    cpu_core   = hw_map.get("cpu_core", "Unknown")

    # slugify for DTS compatible strings
    board_slug = re.sub(r"[^a-z0-9]+", "-", board_name.lower()).strip("-")
    soc_slug   = re.sub(r"[^a-z0-9]+", "-", soc.lower()).strip("-")

    peripherals = [p for p in hw_map.get("peripherals", []) if p["id"] in selected_ids]
    power_rails = hw_map.get("power_rails", [])

    # regulators
    reg_nodes = "\n\n".join(_regulator_node(r) for r in power_rails) if power_rails else ""

    # peripheral nodes
    periph_nodes = "\n\n".join(_peripheral_node(p, i) for i, p in enumerate(peripherals))

    dts = f"""/dts-v1/;

/* Generated by @dt_architect — PDF-to-Gadget Pipeline
 * Board: {board_name}
 * SoC  : {soc}
 * Arch : {arch} ({cpu_core})
 * Date : auto-generated
 */

#include <dt-bindings/interrupt-controller/arm-gic.h>
#include <dt-bindings/gpio/gpio.h>

/ {{
\tcompatible = "vendor,{board_slug}", "vendor,{soc_slug}";
\tmodel = "{board_name}";
\t#address-cells = <2>;
\t#size-cells = <2>;
\tinterrupt-parent = <&gic>;

\tcpus {{
\t\t#address-cells = <1>;
\t\t#size-cells = <0>;

\t\tcpu0: cpu@0 {{
\t\t\tdevice_type = "cpu";
\t\t\tcompatible = "arm,{cpu_core.lower().replace(' ', '-')}";
\t\t\treg = <0>;
\t\t\tenable-method = "psci";
\t\t}};
\t}};

\tpsci {{
\t\tcompatible = "arm,psci-0.2";
\t\tmethod = "smc";
\t}};

\t/* ── Power Regulators ─────────────────────────────── */
{reg_nodes}

\t/* ── Simple Bus ──────────────────────────────────── */
\tsoc: soc {{
\t\tcompatible = "simple-bus";
\t\t#address-cells = <2>;
\t\t#size-cells = <2>;
\t\tranges;

{periph_nodes}
\t}};
}};
"""
    return dts
