"""
@snap_engineer — Snap DevOps Agent
Generates gadget.yaml and snapcraft.yaml for Ubuntu Core Gadget Snap.
"""
import re

def _safe_str(value, default: str = "") -> str:
    return value if isinstance(value, str) else default


_ARCH_MAP = {
    "arm64": {"snap_arch": "arm64", "cross_pkg": "libc6-dev-arm64-cross", "gcc": "gcc-aarch64-linux-gnu"},
    "armhf": {"snap_arch": "armhf", "cross_pkg": "libc6-dev-armhf-cross",  "gcc": "gcc-arm-linux-gnueabihf"},
    "arm":   {"snap_arch": "armhf", "cross_pkg": "libc6-dev-armhf-cross",  "gcc": "gcc-arm-linux-gnueabihf"},
    "amd64": {"snap_arch": "amd64", "cross_pkg": "libc6-dev",              "gcc": "gcc"},
    "x86_64":{"snap_arch": "amd64", "cross_pkg": "libc6-dev",              "gcc": "gcc"},
}

_INTERFACE_MAP = {
    "i2c":      ("i2c", "i2c-{bus}"),
    "spi":      ("spi", "spi-{bus}"),
    "uart":     ("serial-port", "serial-{bus}"),
    "gpio":     ("gpio", "gpio-{bus}"),
    "pwm":      ("pwm", "pwm-{bus}"),
    "usb":      ("raw-usb", "usb-{bus}"),
    "ethernet": ("network", "ethernet-{bus}"),
    "can":      ("can-bus", "can-{bus}"),
    "camera":   ("camera", "camera-{bus}"),
    "hdmi":     ("display-control", "hdmi-{bus}"),
    "other":    ("hardware-observe", "{bus}"),
}

def _gadget_yaml(hw_map: dict, selected: list[dict]) -> str:
    board_name = _safe_str(hw_map.get("board_name"), "Custom")
    soc  = _safe_str(hw_map.get("soc"), "custom-board")
    arch = _safe_str(hw_map.get("arch"), "arm64")
    a    = _ARCH_MAP.get(arch, _ARCH_MAP["arm64"])

    slots_lines = []
    for p in selected:
        ptype  = _safe_str(p.get("type"), "other")
        iface, label_tmpl = _INTERFACE_MAP.get(ptype, _INTERFACE_MAP["other"])
        bus_or_id = _safe_str(p.get("bus")) or _safe_str(p.get("id"), "node")
        label  = label_tmpl.format(bus=bus_or_id.lower())
        desc = _safe_str(p.get("description")) or _safe_str(p.get("name"), "unnamed")
        slots_lines.append(
            f"  {label}:\n    interface: {iface}\n    # {desc}"
        )

    slots_block = "\n".join(slots_lines) if slots_lines else "  # no hardware slots defined"

    return f"""# gadget.yaml — generated by @snap_engineer
# Board: {board_name}  SoC: {soc}  Arch: {a['snap_arch']}

volumes:
  pc:
    bootloader: grub        # replace with u-boot for embedded targets
    structure:
      - name: ubuntu-seed
        role: system-seed
        filesystem: vfat
        type: EF,C12A7328-F81F-11D2-BA4B-00A0C93EC93B
        size: 1200M
      - name: ubuntu-boot
        role: system-boot
        filesystem: ext4
        type: 83,0FC63DAF-8483-4772-8E79-3D69D8477DE4
        size: 750M
      - name: ubuntu-save
        role: system-save
        filesystem: ext4
        type: 83,0FC63DAF-8483-4772-8E79-3D69D8477DE4
        size: 16M
      - name: ubuntu-data
        role: system-data
        filesystem: ext4
        type: 83,0FC63DAF-8483-4772-8E79-3D69D8477DE4
        size: 2G

slots:
{slots_block}
"""


def _snapcraft_yaml(hw_map: dict, selected: list[dict]) -> str:
    board_name = _safe_str(hw_map.get("board_name"), "Custom")
    soc  = _safe_str(hw_map.get("soc"), "custom-board")
    arch = _safe_str(hw_map.get("arch"), "arm64")
    a    = _ARCH_MAP.get(arch, _ARCH_MAP["arm64"])
    slug = re.sub(r"[^a-z0-9]+", "-", board_name.lower()).strip("-")

    slots_section = "\n".join(
        f"  {_INTERFACE_MAP.get(_safe_str(p.get('type'), 'other'), _INTERFACE_MAP['other'])[1].format(bus=(_safe_str(p.get('bus')) or _safe_str(p.get('id'), 'node')).lower())}:"
        for p in selected
    )

    return f"""# snapcraft.yaml — generated by @snap_engineer
name: {slug}-gadget
summary: Gadget snap for {board_name}
description: |
  Auto-generated Ubuntu Core gadget snap for {board_name}.
  SoC: {soc} · Arch: {a['snap_arch']}
  Includes hardware interfaces for selected peripherals.
version: "1.0"
type: gadget
base: core24

architectures:
  - build-on: amd64
    build-for: {a['snap_arch']}

build-packages:
  - {a['cross_pkg']}
  - {a['gcc']}
  - device-tree-compiler

parts:
  gadget-files:
    plugin: nil
    source: meta/
    prime:
      - gadget.yaml

  device-tree:
    plugin: dump
    source: src/
    organize:
      "*.dtb": "boot/"
    prime:
      - "boot/*.dtb"

slots:
{slots_section if slots_section else "  # no slots defined"}
"""


# ── Block diagram constants ────────────────────────────────────────────────────

_COLS    = 8   # grid width — even number, SoC sits in the exact centre
_SOC_W   = 4   # SoC block width (must be even so flanks are equal)
_SIDE_W  = (_COLS - _SOC_W) // 2   # = 2 cols on each side of SoC

# Block column-span per peripheral type (reflects HW complexity / bandwidth)
_TYPE_WIDTH = {
    # ── high-bandwidth / complex pipelines → 3 cols ─────────────────────────
    "ethernet":    3,   # MAC + PHY + DMA engine
    "usb":         3,   # host controller, hub logic
    "hdmi":        3,   # display pipeline, HDCP, audio
    "displayport": 3,   # DP TX controller
    "camera":      3,   # MIPI CSI-2 lanes + ISP
    "mipi_csi":    3,
    "mipi_dsi":    3,
    "pcie":        3,   # root complex + lanes
    # ── medium controllers → 2 cols ─────────────────────────────────────────
    "sata":   2,
    "emmc":   2,
    "sd":     2,
    "sdio":   2,
    "spi":    2,   # DMA + multiple CS lines
    "qspi":   2,
    "can":    2,   # protocol controller + filtering
    "can_fd": 2,
    "i2c":    2,   # multi-device bus + addressing
    "uart":   2,   # duplex serial + flow control
    "usart":  2,
    "i2s":    2,
    "sai":    2,
    "audio":  2,
    "adc":    2,
    "dac":    2,
    "lvds":   2,
    "other":  2,
    # ── simple / single-signal → 1 col ──────────────────────────────────────
    "gpio":     1,
    "pwm":      1,
    "rtc":      1,
    "jtag":     1,
    "swd":      1,
    "watchdog": 1,
}

# Dark fill colours per type
_TYPE_STYLE = {
    "ethernet":    "fill:#0d4f2e,stroke:#1aff7f,color:#fff",
    "usb":         "fill:#0d2f6e,stroke:#4d9fff,color:#fff",
    "hdmi":        "fill:#6e0d0d,stroke:#ff4d4d,color:#fff",
    "displayport": "fill:#6e0d0d,stroke:#ff4d4d,color:#fff",
    "camera":      "fill:#4e0d6e,stroke:#c04dff,color:#fff",
    "mipi_csi":    "fill:#4e0d6e,stroke:#c04dff,color:#fff",
    "mipi_dsi":    "fill:#6e0d0d,stroke:#ff4d4d,color:#fff",
    "pcie":        "fill:#0d3a5e,stroke:#4d8fff,color:#fff",
    "sata":        "fill:#1a2a0d,stroke:#80cc00,color:#fff",
    "emmc":        "fill:#1a2a0d,stroke:#80cc00,color:#fff",
    "sd":          "fill:#1a2a0d,stroke:#80cc00,color:#fff",
    "sdio":        "fill:#1a2a0d,stroke:#80cc00,color:#fff",
    "spi":         "fill:#0d3d5e,stroke:#4dafff,color:#fff",
    "qspi":        "fill:#0d3d5e,stroke:#4dafff,color:#fff",
    "can":         "fill:#6e4e0d,stroke:#ffcc00,color:#fff",
    "can_fd":      "fill:#6e4e0d,stroke:#ffcc00,color:#fff",
    "i2c":         "fill:#3e0d6e,stroke:#9f4dff,color:#fff",
    "uart":        "fill:#0d4e4e,stroke:#00cccc,color:#fff",
    "usart":       "fill:#0d4e4e,stroke:#00cccc,color:#fff",
    "i2s":         "fill:#4e3d0d,stroke:#ffaa00,color:#fff",
    "sai":         "fill:#4e3d0d,stroke:#ffaa00,color:#fff",
    "audio":       "fill:#4e3d0d,stroke:#ffaa00,color:#fff",
    "adc":         "fill:#0d4e3a,stroke:#00ffaa,color:#fff",
    "dac":         "fill:#0d4e3a,stroke:#00ffaa,color:#fff",
    "lvds":        "fill:#5e1a00,stroke:#ff6600,color:#fff",
    "gpio":        "fill:#1a4d1a,stroke:#66ff66,color:#fff",
    "pwm":         "fill:#4d2a0d,stroke:#ff9900,color:#fff",
    "rtc":         "fill:#2a2a4e,stroke:#8888ff,color:#fff",
    "jtag":        "fill:#3a3a3a,stroke:#aaa,color:#ccc",
    "swd":         "fill:#3a3a3a,stroke:#aaa,color:#ccc",
    "watchdog":    "fill:#3a1a1a,stroke:#ff6666,color:#fff",
    "other":       "fill:#2a2a3a,stroke:#888,color:#ccc",
}


def _pack_blocks(items: list[tuple[str, int]], cols: int) -> list[str]:
    """
    Pack (mermaid_token, width) pairs into rows that sum to `cols`.
    Pads incomplete rows with `space:N`.
    Returns list of row strings (without leading indent).
    """
    rows: list[str] = []
    row_tokens: list[str] = []
    row_sum = 0

    for token, w in items:
        if row_sum + w > cols:
            pad = cols - row_sum
            if pad:
                row_tokens.append(f"space:{pad}")
            rows.append(" ".join(row_tokens))
            row_tokens, row_sum = [], 0
        row_tokens.append(token)
        row_sum += w

    if row_tokens:
        pad = cols - row_sum
        if pad:
            row_tokens.append(f"space:{pad}")
        rows.append(" ".join(row_tokens))

    return rows


def _safe_id(raw: str) -> str:
    return re.sub(r"\W+", "_", raw).strip("_") or "node"


def _mermaid_diagram(hw_map: dict, selected: list[dict]) -> str:
    """
    Hub-and-spoke block-beta layout:

      ┌─────────────────────────── Board (full width) ─────────────────────────┐
      │  [big peripheral w=3]  [big peripheral w=3]  [space…]                  │  ← top rows
      │  [left flank w=SIDE]   [    SoC  w=SOC_W  ]  [right flank w=SIDE]     │  ← centre row
      │  [medium/small remaining, packed]                                       │  ← bottom rows
      │  [power rail] [power rail] …                                            │
      └────────────────────────────────────────────────────────────────────────┘

    SoC is the biggest block, centred; large peripherals go on top; small
    peripherals flank the SoC left/right; the rest fill rows below.
    """
    board_name = _safe_str(hw_map.get("board_name"), "Custom")
    soc        = _safe_str(hw_map.get("soc"), "Unknown SoC")
    arch       = _safe_str(hw_map.get("arch"), "arm64")
    cpu_core   = _safe_str(hw_map.get("cpu_core"), "")
    rails      = hw_map.get("power_rails") or []

    # ── Build per-peripheral metadata ─────────────────────────────────────────
    all_meta: list[dict] = []
    for p in selected:
        ptype = _safe_str(p.get("type"), "other")
        w     = _TYPE_WIDTH.get(ptype, 2)
        pid   = _safe_str(p.get("id"), f"node_{len(all_meta)}")
        nid   = _safe_id(pid)
        bus   = _safe_str(p.get("bus")) or pid
        addr  = _safe_str(p.get("address"), "")
        volt  = _safe_str(p.get("voltage"), "")
        pname = _safe_str(p.get("name"), pid)
        label = pname + f"\\n{bus}" + (f" @ {addr}" if addr else "")
        if volt:
            label += f"\\n{volt}"
        token = f'{nid}["{label}"]:{w}'
        all_meta.append({"id": nid, "ptype": ptype, "w": w, "token": token})

    # Sort ascending by width so smallest go to flanks first
    all_meta.sort(key=lambda m: m["w"])

    # ── Assign peripherals to layout zones ────────────────────────────────────
    # "big" (w >= 3) → top rows above SoC, largest-first
    big_meta  = sorted([m for m in all_meta if m["w"] >= 3], key=lambda m: -m["w"])
    rest_meta = [m for m in all_meta if m["w"] < 3]   # smallest first

    # Fill left/right flanks of the SoC row (each flank = _SIDE_W cols)
    left_flank:  list[dict] = []
    right_flank: list[dict] = []
    left_sum = 0
    right_sum = 0
    below_meta: list[dict] = []

    for m in rest_meta:
        if left_sum + m["w"] <= _SIDE_W:
            left_flank.append(m)
            left_sum += m["w"]
        elif right_sum + m["w"] <= _SIDE_W:
            right_flank.append(m)
            right_sum += m["w"]
        else:
            below_meta.append(m)

    # ── Assemble diagram lines ─────────────────────────────────────────────────
    lines: list[str] = ["block-beta", f"  columns {_COLS}"]

    # Board — spans full width
    lines.append(f'  Board["{board_name}"]:{_COLS}')

    # Top rows: large peripherals packed left-to-right
    if big_meta:
        big_tokens = [(m["token"], m["w"]) for m in big_meta]
        for row in _pack_blocks(big_tokens, _COLS):
            lines.append(f"  {row}")

    # Centre row: [left flank] SoC [right flank]
    soc_label = soc + (f"\\n{cpu_core} · {arch}" if cpu_core else f"\\n{arch}")

    def _flank_str(flank: list[dict], total: int) -> str:
        parts = [m["token"] for m in flank]
        pad   = total - sum(m["w"] for m in flank)
        if pad > 0:
            parts.append(f"space:{pad}")
        return " ".join(parts)

    left_str  = _flank_str(left_flank,  _SIDE_W)
    right_str = _flank_str(right_flank, _SIDE_W)
    soc_token = f'SoC["{soc_label}"]:{_SOC_W}'
    lines.append(f"  {left_str} {soc_token} {right_str}")

    # Bottom rows: remaining medium/small peripherals
    if below_meta:
        below_tokens = [(m["token"], m["w"]) for m in below_meta]
        for row in _pack_blocks(below_tokens, _COLS):
            lines.append(f"  {row}")

    # Power rails — rounded shape, width 2
    rail_meta: list[str] = []
    if rails:
        rail_tokens: list[tuple[str, int]] = []
        for r in rails:
            rname = _safe_str(r.get("name"), "vcc")
            rn    = _safe_id(rname)
            v     = _safe_str(r.get("voltage"), "?")
            label = f"{rname}\\n{v}"
            rail_tokens.append((f'{rn}("{label}"):2', 2))
            rail_meta.append(rn)
        for row in _pack_blocks(rail_tokens, _COLS):
            lines.append(f"  {row}")

    # ── Arrows ────────────────────────────────────────────────────────────────
    lines.append("")
    lines.append("  Board --> SoC")
    for m in all_meta:
        lines.append(f"  SoC --> {m['id']}")

    selected_ids = {_safe_str(p.get("id")) for p in selected if _safe_str(p.get("id"))}
    for r in rails:
        rn = _safe_id(_safe_str(r.get("name"), "vcc"))
        for sid in r.get("supplies", []):
            sid_s = _safe_str(sid)
            if sid_s in selected_ids:
                lines.append(f"  {rn} --> {_safe_id(sid_s)}")

    # ── Styles ────────────────────────────────────────────────────────────────
    lines.append("")
    lines.append("  style Board fill:#1a1a2e,stroke:#e0e0ff,color:#e0e0ff,stroke-width:2px")
    lines.append(f"  style SoC fill:#b35c00,stroke:#ff9900,color:#fff,stroke-width:3px")
    for m in all_meta:
        s = _TYPE_STYLE.get(m["ptype"], _TYPE_STYLE["other"])
        lines.append(f"  style {m['id']} {s}")
    for rn in rail_meta:
        lines.append(f"  style {rn} fill:#002244,stroke:#0066cc,color:#cce4ff")

    return "\n".join(lines)


# ── Public API ──────────────────────────────────────────────────────────────────

def run(hw_map: dict, selected_ids: list[str]) -> dict:
    selected = [p for p in hw_map.get("peripherals", []) if _safe_str(p.get("id")) in selected_ids]

    return {
        "gadget_yaml":    _gadget_yaml(hw_map, selected),
        "snapcraft_yaml": _snapcraft_yaml(hw_map, selected),
        "mermaid":        _mermaid_diagram(hw_map, selected),
    }
